apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://charts.jetstack.io' 
    chart: cert-manager
    targetRevision: v1.17.1
    valuesFiles:
      - kubernetes/apps/cert-manager/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
