apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testing.external.secrets.operator
  namespace: default
spec:
  target:
    name: testing.external.secrets.operator
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  
      remoteRef:
        key: testing.external.secrets.operator
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  
      remoteRef:
        key: testing.external.secrets.operator 
        property: password