apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-site
  namespace: argocd
spec:
  project: default
  destination:
    name: "" 
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/esoto6/homelab.git
    targetRevision: master
    path: kubernetes/apps/nginx-site 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false