---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: nginx
spec:
  secretName: nginx-tls-stg
  issuerRef:
    name: letsencrypt-stg
    kind: ClusterIssuer
  dnsNames:
    - nginx.rubberduckops.com