apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
resources:
  - ../../base
patches:
  - path: certificate-dev.yaml
  - path: deployment-dev.yaml
  - path: ingress-dev.yaml
  - path: service-dev.yaml