---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: nginx
spec:
  secretName: letsencrypt-stg
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - nginx.k8s.rubberduckops.com


