apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-hash-admin-password
  namespace: argocd
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: argocd-application-controller  # needs patch access
      restartPolicy: OnFailure
      containers:
        - name: hash-admin-password
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              until kubectl get secret argocd-admin-secret -n argocd; do sleep 5; done
              PASSWORD=$(kubectl get secret argocd-admin-secret -n argocd -o jsonpath="{.data.argocd_password}" | base64 --decode)
              HASH=$(python3 -c "import bcrypt; print(__import__('bcrypt').hashpw(b'$PASSWORD', __import__('bcrypt').gensalt()).decode())")
              kubectl patch secret argocd-secret -n argocd --type merge -p "{\"stringData\":{\"admin.password\":\"$HASH\",\"admin.passwordMtime\":\"$(date +%FT%T%Z)\"}}"
