apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: argocd-admin-secret
    creationPolicy: Owner
  data:
  - secretKey: argocd_password
    remoteRef:
      key: argocd-password