apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    
    - match: Host(`argocd.rubberduckops.com`) && PathPrefix(`/`) # UI Calls
      kind: Rule
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.rubberduckops.com`) && PathPrefix(`/swagger-ui`) #Swagger UI 
      priority: 11
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.rubberduckops.com`) && PathPrefix(`/api`) #API Calls
      priority: 12
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.rubberduckops.com`) && Header(`Content-Type`, `application/grpc`)
      kind: Rule
      priority: 13
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls