apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.rubberduckops.com`) && PathPrefix(`/api`) #API Calls
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.rubberduckops.com`) && (PathPrefix(`/`) || PathPrefix('/swagger-ui')) # UI Calls
      kind: Rule
      priority: 11
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.rubberduckops.com`) && Header(`Content-Type`, `application/grpc`)
      kind: Rule
      priority: 12
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls