apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  namespace: argocd
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  version: 8.3.8

resources:
- namespace.yaml
- ingress.yaml
- certificate.yaml
- external-secret-admin.yaml 