global:
  domain: argocd.rubberduckops.com
configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
  secret:
    admin:
      existingSecret: argocd-admin-secret
      passwordKey: argocd_password
# secret:
#   createSecret: false
server:
  ingress:
    enabled: false
  server:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8080
  extraArgs:
    - --insecure
    