global:
  domain: argocd.rubberduckops.com
configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
    accounts.homepage: apiKey
  secret:
    admin:
      existingSecret: argocd-admin-secret
      passwordKey: argocd_password
  rbac:
    policy.csv: |
      g, homepage, role:readonly
secret:
  createSecret: false
server:
  ingress:
    enabled: false
  server:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8080
  extraArgs:
    - --insecure
    