apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://charts.argoproj.io'
    targetRevision: '7.8.23' 
    chart: argo-cd
    helm:
      values: |
        global:
          domain: argocd.rubberduckops.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true