apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    name: "" 
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://charts.argoproj.io' 
    targetRevision: 'v3.30.0'
    values:
      path: kubernetes/apps/argocd/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true