apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: generated-config
          emptyDir: {}
        - name: logs
          emptyDir: {}
      initContainers:
        - name: generate-config
          image: alpine:3.18
          command:
            - sh
            - -c
            - |
              set -e
              apk add --no-cache gettext yq

              echo "Interpolating and validating configs..."
              mkdir -p /generated

              envsubst < /configmap/services.yaml > /generated/services.yaml

              echo "Copying other config files..."
              cp /configmap/custom.js /generated/ || true
              cp /configmap/custom.css /generated/ || true
              cp /configmap/bookmarks.yaml /generated/ || true
              cp /configmap/widgets.yaml /generated/ || true
              cp /configmap/settings.yaml /generated/ || true
              cp /configmap/kubernetes.yaml /generated/ || true
              cp /configmap/docker.yaml /generated/ || true
          envFrom:
            - secretRef:
                name: homepage-secrets
          volumeMounts:
            - name: homepage-config
              mountPath: /configmap
              readOnly: true
            - name: generated-config
              mountPath: /generated
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.rubberduckops.com
          envFrom:
            - secretRef:
                name: homepage-secrets
          volumeMounts:
            - name: generated-config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs