apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik
  namespace: traefik
  releaseName: traefik
  repo: https://traefik.github.io/charts
  valuesFile: values.yaml
  version: 35.2.0

resources:
- namespace.yaml