deployment:
  enabled: true
  replicas: 1 

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"

ports:
  web:
    redirectTo: websecure
  websecure:
    tls: 
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  KubernetesCRD:
    enabled: true
    ingressClasss: "traefik-external"
  kubernetesIngress:
    enabled: true

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.1.155
