apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server-cert
  namespace: external-secrets-system
spec:
  secretName: bitwarden-tls-certs
  issuerRef:
    name: ca-issuer
    kind: Issuer
  dnsNames:
    - bitwarden-sdk-server
    - bitwarden-sdk-server.external-secrets-system
    - bitwarden-sdk-server.external-secrets-system.svc
    - bitwarden-sdk-server.external-secrets-system.svc.cluster.local
  commonName: bitwarden-sdk-server
  duration: 2160h 
  renewBefore: 360h
  subject:
    organizationalUnits:
    - "Bitwarden SDK Server"
    organizations:
    - "External Secrets"
  usages:
  - server auth
  - client auth