apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  target:
    name: cloudflare-token
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: cloudflare-token
          kind: ClusterSecretStore  
      remoteRef:
        key: cloudflare-token
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: cloudflare-token
          kind: ClusterSecretStore  
      remoteRef:
        key: cloudflare-token
        property: password