apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb
  namespace: metallb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metallb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metallb
    spec:
      containers:
        - name: metallb
          image: metallb/metallb:v0.11.0
---
apiVersion: v1
kind: Service
metadata:
  name: metallb
  namespace: metallb
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: metallb