apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-stg
    kind: ClusterIssuer
  commonName: argocd.k8s.rubberduckops.com
  dnsNames:
    - argocd.k8s.rubberduckops.com
