global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: argocd.k8s.rubberduckops.com
configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
server:
  service:
    type: LoadBalancer

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-stg
    hosts:
      - argocd.k8s.rubberduckops.com
    tls:
      - hosts:
          - argocd.k8s.rubberduckops.com
        secretName: argocd-tls