apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: traefik
spec:
  secretName: traefik-tls
  issuerRef:
    name: letsencrypt-prd
    kind: ClusterIssuer
  dnsNames:
    - traefik.rubberduckops.com