---
- name: Reset Cluster
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    metallb_state: absent
    cert_manager_state: absent
    external_secrets_state: absent

  tasks:
    - name: Uninstall MetalLB
      import_tasks: tasks/metallb.yaml
    - name: Uninstall Cert-Manager
      import_tasks: tasks/cert-manager.yaml
    - name: Uninstall external-secrets
      import_tasks: tasks/external-secrets.yaml