---
- name: Setup Kubernetes Cluster Components
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/secrets.yaml
    - vars/versions.yaml

  tasks:
    - name: Install MetalLB
      import_tasks: tasks/metallb.yaml

    - name: Install Cert-Manager
      import_tasks: tasks/cert-manager.yaml

    - name: Setup External Secrets
      import_tasks: tasks/external-secrets.yaml

    # - name: Install Traefik
    #   import_tasks: tasks/traefik.yaml

    # - name: Run validation checks
    #   import_tasks: tasks/checks.yaml
    
    # - name: Install ArgoCD
    #   import_tasks: tasks/argocd.yaml

