apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  namespace: external-secrets
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
  valuesFile: values.yaml
  version: 0.16.2