apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: trivy-operator
  namespace: trivy-system
  releaseName: trivy-operator
  repo: https://aquasecurity.github.io/helm-charts/
  valuesFile: values.yaml
  version: 0.26.0

