apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - name: argocd
          #   path: applications/argocd
          #   namespace: argocd
          # - name: external-secrets
          #   path: applications/external-secrets
          #   namespace: external-secrets
          - name: cert-manager
            path: applications/cert-manager/overlays/dev
            namespace: cert-manager
            syncwave: "1"
          # - name: nginx
          #   path: applications/nginx/overlays/dev
          #   namespace: nginx
          # - name: trivy-operator
          #   path: applications/trivy-operator/base
          #   namespace: trivy-system
          - name: traefik
            path: applications/traefik
            namespace: traefik
  template:
    metadata:
      name: '{{name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/esoto6/homelab.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true