apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - name: argocd
          #   namespace: argocd
          #   chart: argo-cd
          #   repo: https://argoproj.github.io/argo-helm
          #   version: 7.9.0
          #   valueFiles: applications/argocd/values.yaml
            # sync-wave: 0
          # - name: rancher
          #   namespace: cattle-system
          #   path: applications/rancher
          #   chart: rancher
          #   repo: https://releases.rancher.com/server-charts/latest
          #   version: '2.11.1'
          #   valueFiles: applications/rancher/values.yaml
          #   sync-wave: 3
          - name: trivy-operator
            namespace: trivy-system
            chart: trivy-operator
            repo: https://aquasecurity.github.io/helm-charts/
            version: 0.28.0
            valueFiles: "applications/trivy-operator/values.yaml"
  template:
    metadata:
      name: '{{name}}'
      # annotations:
      #   argocd.argoproj.io/sync-wave: '{{sync-wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        chart: '{{chart}}'
        repoURL: '{{repo}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
            - '{{valueFiles}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
