apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    releaseName: rancher
    namespace: cattle-system
    version: 2.11.1 
    valuesFile: values.yaml
    includeCRDs: true