apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: rancher
  namespace: cattle-system
  releaseName: rancher
  repo: https://releases.rancher.com/server-charts/stable
  valuesFile: values.yaml
  version: 2.12.1

resources:
  - certificate.yaml
  - eso-rancher-bootstrap.yaml