---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stg
  namespace: cert-manager
spec:
  acme:
    email: "edwin.soto03@gmail.com"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-stg
    solvers:
      - dns01:
          cloudflare:
            email: "edwin.soto03@gmail.com"
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token