---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site-rubberduckops-tls
  namespace: dev
spec:
  secretName: site-rubberduckops-tls  
  issuerRef:
    name: letsencrypt-prod  
    kind: ClusterIssuer
  dnsNames:
    - site.rubberduckops.com