---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
            - name: https 
              containerPort: 443
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-site
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-site
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`test-site.rubberduckops.com`)
      kind: Rule
      services:
        - name: nginx-site
          port: 80
#   tls:
#     secretName: test-site-rubberduckops-tls

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: test-site-rubberduckops-tls
#   namespace: dev
# spec:
#   secretName: test-site-rubberduckops-tls  
#   issuerRef:
#     name: letsencrypt-prod  
#     kind: ClusterIssuer
#   dnsNames:
#     - test-site.rubberduckops.com

