---
- name: Reset Cluster
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/app-secrets.yaml
    - vars/app-versions.yaml

  vars: 
    metallb_state: absent
    cert_manager_state: absent
    external_secrets_state: absent
    traefik_state: absent
    argocd_state: absent

  tasks:
    - import_tasks: tasks/1.metallb-app.yaml
      vars:
        kubeconfig_path: "~/.kube/config"
        metallb_namespace: "{{ metallb.namespace }}"
        metallb_chart: "{{ metallb.chart }}"
        metallb_version: "{{ metallb.version }}"
        metallb_repo: "{{ metallb.repo }}"
        metallb_alias: "{{ metallb.repository_alias }}"
        metallb_addresses: "{{ ip_addresses }}"

    # - name: Uninstall Cert-Manager
    #   import_tasks: tasks/cert-manager.yaml
    # - name: Uninstall external-secrets
    #   import_tasks: tasks/external-secrets.yaml
    # - name: Uninstall Traefik
    #   import_tasks: tasks/traefik_app.yaml
    # - name: Uninstall ArgoCD
    #   import_tasks: tasks/argocd.yaml