- name: Install ArgoCD in GitOps Manner
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure kubeconfig path is set
      set_fact:
        kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/config"

    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Install ArgoCD manifests
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        kubeconfig: "{{ kubeconfig_path }}"
    
    - name: Wait for argocd pods to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: argocd
      register: argocd_pods
      until: argocd_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 2
      retries: 20
      delay: 10
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply ArgoCD Bootstrap Application (Self-Managing)
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: root-app
            namespace: argocd
          spec:
            destination:
              namespace: argocd
              server: https://kubernetes.default.svc
            project: default
            source:
              repoURL: "https://github.com/esoto6/homelab.git"
              targetRevision: master
              path: kubernetes/apps
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - Validate=false
        kubeconfig: "{{ kubeconfig_path }}"