kubernetes:
  ingressClass: traefik
  ingressClassResource:
    name: traefik
    enabled: true

deployment:
  replicas: 1

service:
  type: LoadBalancer

dashboard:
  enabled: true
  domain: traefik.rubberduckops.com

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    matchRule: "Host(`traefik.rubberduckops.com`)"
    tls:
      secretName: wildcard-cert-tls