apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: nginx-app
spec:
  project: default
  source:
    repoURL: https://github.com/esoto6/homelab
    targetRevision: HEAD
    path: applications/nginx-app
  destination:
    namespace: nginx-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true