apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: argocd-admin-secret
    creationPolicy: Merge
  data:
    - secretKey: username
      remoteRef:
        key: "argocd-username"
        property: username
    - secretKey: password
      remoteRef:
        key: "argocd-password"
        property: password
