apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    namespace: argocd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    version: 7.9.0
